In [ ]:
import numpy as np

class car():
    def __init__(self, type, speed):
        self.type = type
        self.speed = speed
    def accelerate(self):
        self.speed += 10 


In [ ]:
car1 = car('bmw', 200)

print(car1.type)
print(car1.speed)

car1.accelerate()
print(car1.speed)

bmw
200
210


In [1]:
import numpy as np
import random

class Network(object):                         # Network라는 틀을 만들거임
    def __init__(self, sizes):                  # 그 Network라는 class에 들어가는 변수를 입력하는데 여기서는 그것이 sizes임
      self.num_layers = len(sizes)              # init에서 들어간 sizes에 들어간 리스트의 길이를 num_layers에 할당
      self.sizes = sizes                        # init에서 들어갔던 sizes에 들어간 그 리스트 자체를 sizes에 할당
      self.biases = [np.random.randn(y, 1) for y in sizes[1:]]      # init에 들어간 sizes에 있는 리스트에서 2번째 성분부터 y개의 component가 있는 (y,1)행렬을 만들것임
      self.weights = [np.random.randn(y, x)                         # init에 들어간 sizes에 있는 리스트에서 
          for x, y in zip(sizes[:-1], sizes[1:])]
      
    def sigmoid(z):
         return 1.0/(1.0+np.exp(-z))
    
    def feedforward(self, a):
        """입력이 "a"이면 네트워크의 출력을 반환한다."""
        for b, w in zip(self.biases, self.weights):
            a = sigmoid(np.dot(w, a)+b)
        return a
    
    def SGD(self, training_data, epochs, mini_batch_size, eta, test_data=None):
        """미니 배치 확률적 경사 하강법을 이용해 뉴럴 네트워크를 학습시킨다. "training_data"는 학습 입력과 이상적인 출력을 나타내는 튜플 "(x, y)"의 리스트이다. 다른 파라미터들은 따로 설명할 필요가 없다. 
        "test_data"가 주어지면 각 에폭마다 테스트 데이터에 대해 네트워크를 평가하고, 진행 상황을 출력한다. 
        이는 진행 상황을 확인할 수 있지만 성능을 상당히 저하시킨다."""
        if test_data: 
            n_test = len(test_data)
        n = len(training_data)
        for j in range(epochs):
            random.shuffle(training_data)
            mini_batches = [
                training_data[k:k+mini_batch_size]
                for k in range(0, n, mini_batch_size)]
            for mini_batch in mini_batches:
                self.update_mini_batch(mini_batch, eta)
            if test_data:
                print( "Epoch {0}: {1} / {2}".format(
                    j, self.evaluate(test_data), n_test))
            else:
                print( "Epoch {0} complete".format(j))

    def update_mini_batch(self, mini_batch, eta):
        """하나의 미니 배치에 대해 역전파를 이용하는 경사 하강법을 적용하여
        네트워크의 가중치와 편향을 업데이트한다. 
        "mini_batch"는 튜플 "(x, y)"의 리스트이며, "eta"는 학습률이다."""
        nabla_b = [np.zeros(b.shape) for b in self.biases]
        nabla_w = [np.zeros(w.shape) for w in self.weights]
        for x, y in mini_batch:
            delta_nabla_b, delta_nabla_w = self.backprop(x, y)
            nabla_b = [nb+dnb for nb, dnb in zip(nabla_b, delta_nabla_b)]
            nabla_w = [nw+dnw for nw, dnw in zip(nabla_w, delta_nabla_w)]
        self.weights = [w-(eta/len(mini_batch))*nw 
                 for w, nw in zip(self.weights, nabla_w)]
        self.biases = [b-(eta/len(mini_batch))*nb 
                 for b, nb in zip(self.biases, nabla_b)]


In [ ]:
data = Network([2,3,1])

input = [5, 8]

print(data.feedforward(input))

[[0.26411212 0.40306384 0.42121235]]


In [ ]:
print(data.weights[0])
print(data.weights[1])

[[ 0.35920865  0.67604015]
 [ 1.00438691 -0.48930045]
 [ 0.78308636  1.09790253]]
[[ 0.71972951  0.42255189 -0.44684208]]
